language: python
sudo: false
python:
- '2.7'
- '3.4'
addons:
    apt:
        sources:
            - avsm
        packages:
            - ocaml-nox
            - opam
before_install:
- wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
- chmod +x miniconda.sh
- bash miniconda.sh -b -p $HOME/miniconda
- export PATH="/home/travis/miniconda/bin:$PATH"
- conda update --yes conda
- conda install --yes python="$TRAVIS_PYTHON_VERSION" numpy scipy matplotlib sympy networkx
    nose h5py pexpect
- pip install -i https://pypi.binstar.org/pypi/simple pygraphviz==1.3rc1
- pip install python-coveralls
- wget "http://www.csb.pitt.edu/Faculty/Faeder/?smd_process_download=1&download_id=142"
    -O BioNetGen-2.2.6-stable.tar.gz
- tar xzf BioNetGen-2.2.6-stable.tar.gz
- export BNGPATH=`pwd`/BioNetGen-2.2.6-stable
# First install ocamlfind via opam (needed to build KaSim/KaSa)
- opam init -a git://github.com/ocaml/opam-repository && eval $(opam config env)
- opam install ocamlfind --yes
# Install KaSim/KaSa
- git clone https://github.com/Kappa-Dev/KaSim.git
- cd KaSim
- make all
- export PATH=$PATH:`pwd`
- cd ../
install:
  python setup.py build --build-lib=build/lib
script:
  nosetests build/lib/pysb --with-coverage --cover-inclusive --cover-package=build/lib/pysb
after_success:
  coveralls
