name: build
on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 4
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@master
    - name: Setup conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      shell: bash -l {0}
      run: |
        conda install --yes -c conda-forge numpy scipy matplotlib sympy nose h5py pexpect pandas networkx pydot codecov mock cython
    - name: Install extra dependencies for python 3.7 and 3.6
      shell: bash -l {0}
      if : matrix.python-version == 3.6 || matrix.python-version == 3.7
      run: |
        conda install --yes -c SBMLTeam python-libsbml
        pip install libroadrunner twine
    - name: Install extra dependencies for python 3.8
      shell: bash -l {0}
      if : matrix.python-version == 3.8
      run: |
        pip install python-libsbml
        pip install twine
    - name: Install BioNetGen, Kappa, StochKit and Atomizer
      shell: bash -l {0}
      run: |
        conda install --yes -c alubbock kappa stochkit bionetgen atomizer
    - name: Install and test pysb
      shell: bash -l {0}
      run: |
        python setup.py build --build-lib=build/lib
        python setup.py sdist && twine check dist/*
        nosetests build/lib/pysb --with-coverage --cover-inclusive --cover-package=build/lib/pysb -a '!gpu'